application: helloworld0923
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /.*
#  script: phase1.application
- url: /.*
  script: trend.app
  login: admin

libraries:
- name: webapp2
  version: latest

